name: TDD

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Install Dependencies
        run: yarn install

      - name: Check lint
        run: yarn lint

      - name: Test
        run: yarn test

